_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  prediction_lengths: [7, 14, 21, 30] # 1 week, 2 weeks, 3 weeks, 1 month
  context_lengths: [30] # 1 month
  patch_sizes: [16, 32]
