_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: btc_data_eval
  offset: 2557
  eval_length: 1004
  prediction_lengths: [7, 14, 21, 30, 60]
  context_lengths: [7, 14, 21, 30, 60]
  patch_sizes: [16, 32]
