_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  prediction_lengths: [168, 336, 504, 720]
  context_lengths: [168, 720]
  patch_sizes: [8, 16, 32, 64, 128]
